### ISSUE TITLE
 Cannot read property 'packet' of null

### ISSUE THREAD

**Issue by marqueeeeeee** [mcollina/aedes-persistence-mongodb#2]
Hi i'm having some error in mongodb persistence. i tried publishing 2 message with qos 2 while the receiver is offline. once it goes online it receives 3 messages and then crashed.

C:\nodejs\node_modules\aedes-persistence-mongodb\node_modules\mongojs\node_mod
ules\mongodb\lib\utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'packet' of null
    at C:\nodejs\node_modules\aedes-persistence-mongodb\persistence.js:321:16
    at C:\nodejs\node_modules\aedes-persistence-mongodb\node_modules\mongojs\l
ib\collection.js:139:7
    at C:\nodejs\node_modules\aedes-persistence-mongodb\node_modules\mongojs\n
ode_modules\mongodb\lib\collection.js:1162:18
    at handleCallback (C:\nodejs\node_modules\aedes-persistence-mongodb\node_m
odules\mongojs\node_modules\mongodb\lib\utils.js:96:12)
    at C:\nodejs\node_modules\aedes-persistence-mongodb\node_modules\mongojs\n
ode_modules\mongodb\lib\collection.js:1196:5
    at commandCallback (C:\nodejs\node_modules\aedes-persistence-mongodb\node_
modules\mongojs\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\
server.js:943:9)
    at Callbacks.emit (C:\nodejs\node_modules\aedes-persistence-mongodb\node_m
odules\mongojs\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\s
erver.js:116:3)

**Comment by mcollina** [comment]
Solved in the just released v2.2.0.
