### ISSUE TITLE
Only retained collection working

### ISSUE THREAD

**Issue by robertsLando** [mcollina/aedes-persistence-mongodb#25]
Since I'm using Aedes I see that the only one collection that appears is `retained`. Where are `packets`, `subscriptions`, `clients` etc?

I set up aedes as follow:

```js  
    var aedesSettings = {
    port: 1883,
    persistence: require('aedes-persistence-mongodb')({
      db: mongoose.connection.useDb('aedesMqtt')
    })
  };

  broker = require('aedes')(aedesSettings);
```

**Comment by robertsLando** [comment]
@mcollina Any update on this?

**Comment by mcollina** [comment]
I'd recommend you to check out the code and send a docs PR explaining the collections. The code is fully tested, so you should be able to read the source. I have no time to document how this module works internally.

**Comment by robertsLando** [comment]
@mcollina Seems that this happens if you don't specify a ttl in options. If I add ttl options all collections are working

**Comment by robertsLando** [comment]
Based on this. I think that existing ttl options should expect a different ttl for retained messages. 

I suggest something like: 

```js
ttl: {
      packets: {
           incoming: 300,
           outgoing: 500,
           will: 500,
           retained: -1 //persistent
      }
      subscriptions: 300
  }
```

If the ttl is -1 the index should not be created. To keep back compatibility a check can be done at start to use that ttl value for all packets
