### ISSUE TITLE
Not all packets are delivered to subscribed clients

### ISSUE THREAD

**Issue by robertsLando** [mcollina/aedes-persistence-mongodb#27]
Seems that there is a big bug with this peristence. When I publish 15 messages simultaniously I only get 5/6 of them in a client subscribed.

What could be this related to? I have tried to revert to some old versions but nothing changes. If I remove the persistence all messages are received from clients correctly so the problem must be here.

**Comment by robertsLando** [comment]
Tested with persistence redis and this bug isn't present. That's really strange

**Comment by robertsLando** [comment]
After some dig into the problem seems that packets are received by the borker correctly but the function [dedupe](https://github.com/mcollina/aedes/blob/master/lib/client.js#L151) of `aedes/lib/client.js` returns false [here](https://github.com/mcollina/aedes/blob/master/lib/client.js#L116) for some packets and them are not forwarded to the client.

I still don't know why this happens only when using `aedes-persistence-mongodb` but that's the problem that prevents all my messages to be forwarded to the client. 

Any help please? @mcollina

**Comment by mcollina** [comment]
Which version of aedes are you using? Count that master (not released) needs the fixes in from aedes-persistence to work.

Anyway, as I said elsewhere, *I have no time to investigate bugs in this module* for the next few weeks.

A PR with a fix will be highly appreciated anyway.
Il 17 dic 2019, 05:56 -0500, Daniel Lando <notifications@github.com>, ha scritto:

**Comment by robertsLando** [comment]
Aedes version 0.39.0

**Comment by robertsLando** [comment]
Seems like packets are processed in the wrong order. If I remove mongodb persistence packets are parsed sorted by the brokerCounter (from the one with the borkerCounter value to the one with the higher value). If I use the mongodb persistence the order used to process packets is different. I will investigate more and come back to you with a fix (hope)

**Comment by robertsLando** [comment]
Ok I have find out why this happens.

When `retain` flag is set to `true` broker needs to store the ratained message using the persistence selected than emits the packets and here is where `client.deliverQoS` is called. 

The problem is that when we are using in-memory persistences like redis the packets are stored in the same order they arrive, if the persistence is mongodb the store operation takes a little more and it's not sure that all insert operations will finish at the same time. 

When this happens the dedupe function will get packets in the wrong order and `client.duplicates[id]` will contain the last `packet.brokerCounter` that could be higher than the next packet processed so this causes `dedupe` to return false and reject the forward.

Now, I don't know what you prefer but I think this should be fixed in aedes and not in this persistence. 

@getlarge @gnought do you have any ideas?

**Comment by getlarge** [comment]
Sorry @robertsLando, that seems quite tricky and i don't have a clear idea to fix this in aedes client.js.
Quite randomly i could suggest to compare packets messageId with broker.counter.

**Comment by gnought** [comment]
@robertsLando could you provide a working code for us to have a check?

**Comment by robertsLando** [comment]
What you mean with “a working code”? You mean something to replicate the bug? It is simple to replicate, I have used node-red to test it just by creating a flow that subscribes to a topic x and a node that sends 20 messages with a for loop. Just 5/6 messages are catched by the subscribed node when using mongodb persistence, all messages wheb using others persistence. By using nodejs inspect I saw that the problem was the one I have described in previous comment. 

Daniel

**Comment by mcollina** [comment]
@robertsLando I mean that we need a Node.js script that reproduces the problem. In other term, an integration test.

**Comment by robertsLando** [comment]
Here the test code @mcollina @gnought 

```js

var mqtt = require('mqtt')
var Promise = require('bluebird')
const persistence = require('aedes-persistence-mongodb')


var aedes = require('aedes')({
    persistence: persistence({
        url: 'mongodb://127.0.0.1/aedes-test'
    })
})

const startClient = (ID) => {
    return new Promise((resolve) => {
        var client = mqtt.connect('mqtt://localhost', { clientId: ID })

        client.on('connect', function () {
            resolve(client)
        })
    })
}

var server = require('net').createServer(aedes.handle)

// fired when a client connects
aedes.on('client', function (client) {
    var cId = client ? client.id : null;
    console.log('Client Connected: \x1b[33m' + cId + '\x1b[0m')
})

// fired when a client disconnects
aedes.on('clientDisconnect', function (client) {
    var cId = client ? client.id : null;
    console.log('Client Disconnected: \x1b[33m' + cId + '\x1b[0m')
})

aedes.on('subscribe', function (subscriptions, client) {
    console.log('MQTT client \x1b[32m' + (client ? client.id : client) +
        '\x1b[0m subscribed to topics: ' + subscriptions.map(s => s.topic).join('\n'))
})

aedes.on('unsubscribe', function (subscriptions, client) {
    console.log('MQTT client \x1b[32m' + (client ? client.id : client) +
        '\x1b[0m unsubscribed to topics: ' + subscriptions.join('\n'))
})

aedes.on('publish', async function (packet, client) {
    console.log('Client \x1b[31m' + (client ? client.id : 'BROKER_' + aedes.id) + '\x1b[0m has published', packet.payload.toString(), 'on', packet.topic)
})


server.listen(1883, async function () {

    var client = await startClient('TESTER')

    var topic = 'my/topic'
    var totalSend = 100

    client.subscribe(topic)

    var counter = 0

    client.on('message', function (topic, message) {
        counter++
    })

    for (let i = 0; i < totalSend; i++) {
        client.publish(topic, JSON.stringify({ index: i }), { qos: 1, retain: true })
    }

    setTimeout(function () {

        console.log("Messages sent:", totalSend);
        console.log("Messages received:", counter);

        console.log("--------DONE---------");
        process.exit(0)

    }, 2000)
})

```

**Comment by mcollina** [comment]
You need to wait for the subscription callback to be called before starting to publish.

**Comment by robertsLando** [comment]
@mcollina The debug log was showing subscription log before the publish, anytway I have fixed the program to wait for the usbscription before sending messages, the problem is still there anyway

**Comment by mcollina** [comment]
I would do #28 first. It _might_ solve the problem on its own, as there are a ton of fixes in the base machinery.

After that, I would need some help to fix this. I'm not using this module at all and I have no bandwidth to do the research to investigate _why_.

**Comment by robertsLando** [comment]
@mcollina There is no reason in search *why*, I have already explained the problem with in details. I think that this is not strictly related to this library but by aedes itself and should be fixed. There is also still some problems with client connections that needs to be fixed and is not related to the persistence. I'm using aedes in a production environment and I wish to don't revert back to mosca, I like aedes and I hope it will 'replace' mosca leading position in the near future

**Comment by mcollina** [comment]
Feel free to send a PR to fix this ;).

**Comment by robertsLando** [comment]
@mcollina would it be possibile to assign borkerCounter to packet after it is stored? This would fix the problem... But this would need to edit also aedes-packet

**Comment by mcollina** [comment]
How does Redis fixes this?

**Comment by robertsLando** [comment]
@mcollina Redis doesn't fixes this. This probelm doesn't shows up in redis because all read/write operations in redis are processed and ultimated in the order they come, in mongodb it doesn't (not in most cases).

When a packet is received this functions are called in sequence:

```js
var publishFuncsQoS = [
  storeRetained,
  enqueueOffline,
  emitPacket,
  callPublished
]
```

If I receive 20 packets in the same time redis wrote the from 1 to 20 emitPacket will send packets in the orer 1 2 3 ... 20 . In mongodb the store operation is slower and takes a 'random' time and packets can be emitted in the wrong order. 

When this happens the dedupe function will discard some packets because it keeps track of the last processed packet brokerCounter and if next packet has a lower brokerCounter it returns false and it is discarded

**Comment by robertsLando** [comment]
The problem must be fixed in aedes and not in this persistence. Actually I have fixed my problem on my own repo of aedes by removing dedupe funcion check but if it is useful (I don't know why and how there could be duplicates packets received) we must think about another solution

**Comment by mcollina** [comment]
Duplicates happens because of subscription overlaps.

Aedes assumes that _writes happens in order_. We might want to set `w: 0` when we save the retain method... it might fix this.

Another option is to use a https://mongodb.github.io/node-mongodb-native/3.4/api/Collection.html#bulkWrite internally (one at a time) for storing retained messages.

**Comment by robertsLando** [comment]
@mcollina What you think is more performant? First or second? 

I'm not sure the `w:0` method would work

**Comment by robertsLando** [comment]
I have tried with something like: 

 ```js
MongoPersistence.prototype.storeRetained = function (packet, cb) {
  if (!this.ready) {
    this.once('ready', this.storeRetained.bind(this, packet, cb))
    return
  }
  var criteria = { topic: packet.topic }
  var bulk = this._cl.retained.initializeOrderedBulkOp()

  if (packet.payload.length > 0) {
    bulk.find(criteria).upsert().updateOne(decoratePacket(packet, this._opts))
  } else {
    bulk.find(criteria).deleteOne()
  }

  bulk.execute(cb)
}
```

But seems not fixing the problem

**Comment by mcollina** [comment]
You'll need to implement something similar to https://github.com/mcollina/ioredis-auto-pipeline/blob/master/index.js where things are appended to the bulk operation while the previous one is runnning.

**Comment by robertsLando** [comment]
I don’t find any documentation that explain how and if this is possible to do with mongodb bulk operations. 

Daniel
