### ISSUE TITLE
Update aedes-cached-persistence to v8.0.0

### ISSUE THREAD

**Issue by mcollina** [mcollina/aedes-persistence-mongodb#28]
To release aedes master, I would love to get this module up to date as well.

Can somebody help?

**Comment by robertsLando** [comment]
Tell me what needs to be implemented

**Comment by mcollina** [comment]
update the dependency and fix broken tests

**Comment by robertsLando** [comment]
I have already tried to update the dependency. About broken tests the only problem is with the messageId property that should be undefined but in mongodb if you set a valut to undefined it will be set to null on mongo and the test fails.

Daniel

**Comment by mcollina** [comment]
Then we should update the test to accept both `null` and `undefined`.

**Comment by robertsLando** [comment]
The test is inside aedes-persistence abstract.js. Will send you a pr for that

**Comment by robertsLando** [comment]
@mcollina this can be closed
