### ISSUE TITLE
auto_reconnect deprecated?

### ISSUE THREAD

**Issue by wuhkuh** [mcollina/aedes-persistence-mongodb#5]
Good evening,

According to the [docs](http://mongodb.github.io/node-mongodb-native/2.0/tutorials/connection_failures/) the autoReconnect option in the MongoClient works like the following example:
`mongodb://localhost:27017/test?autoReconnect=false`

While in the source code it's implemented like this:
`var conn = this._opts.url || 'mongodb://127.0.0.1/aedes?auto_reconnect=true'`

Should I send a PR which replaces last line to:
`var conn = this._opts.url || 'mongodb://127.0.0.1/aedes?autoReconnect=true'`?

**Comment by mcollina** [comment]
Please do! :)

**Comment by wuhkuh** [comment]
Closed. See #6
