### ISSUE TITLE
Undefined payload being published for undelivered messages

### ISSUE THREAD

**Issue by GavinDmello** [mcollina/aedes-persistence-mongodb#7]
An empty payload is received. I noticed 
<a>https://github.com/mcollina/aedes-persistence-mongodb/blob/master/persistence.js#L294 </a>. But there isn't any buffer in the document. Removing the if condition worked for me.

**Comment by GavinDmello** [comment]
I guess this is happening because I'm publishing a string in the payload

**Comment by mcollina** [comment]
@GavinDmello how do you propose we fix that? Removing the condition is a no-go, but we should support strings as well :).

**Comment by GavinDmello** [comment]
Yea. The issue got resolved when I published a Buffer object. 
We should support strings though.

**Comment by mcollina** [comment]
Should be fixed by #8
